### ISSUE TITLE
[Tracking] Draft a new information architecture plan

### ISSUE THREAD

**Issue by lsgunn-teleport** [gravitational/docs#370]
The docs website could use some freshening up to make it easier to find information and provide a better flow for information consumers. The current site is focused around feature sets but not so much on the user journey or use case scenarios. The docs team would like to prepare a new information architecture plan that we can then look to implement in the following quarters. 

The goal for this quarter is to sketch out an information architecture that focuses on: 
- user journey
- use-case scenarios
- information types (concept, how-to, tutorial, and reference)
- access to alternative resources (Teleport Labs, videos, case studies)

As part of this task for this quarter, we'd like to solicit feedback on the structure before we commit to any large scale changes.

Related issues:
- https://github.com/gravitational/teleport/issues/21313
- https://github.com/gravitational/teleport/issues/15016
- https://github.com/gravitational/teleport/issues/11263
- https://github.com/gravitational/teleport/issues/19192
- https://github.com/gravitational/teleport/issues/24120
- https://github.com/gravitational/teleport/issues/29980 (not specifically being addressed, but to keep in mind as part of the planning process)
```[tasklist]
### Tasks
- [x] https://github.com/gravitational/docs/issues/391
- [ ] Align with product marketing messaging and platform positioning
- [ ] https://github.com/gravitational/docs/issues/392
- [ ] Expand the Teleport style guide
- [ ] Draft Quick start topics
- [ ] Revise, restructure, and update Install, Upgrade, and Remove topics
- [ ] Review and restructure machine identity topics
```

**Comment by ptgott** [comment]
Closing since we are working off of another reorganization plan.
